# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10748ba05aa13d9233fb4bd70cc7f584368c5b8795e86f51774f93602ab1666d0848361d90afa73c79f1701cb1bd34419999d853771e8ab847ad98c65238040f

test:
  secret_key_base: 45c6b014116a8b2bfe1d9ce1f2be71c58414fa08c222199a492b5fcb67a7c1e14b4d87031ddfcebae76a79d187a4f472979580ea9e2d911a6363f3db7db65289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
